# CI/CD Pipeline for Build, Test, Package, and Publish
name: Build-Test-Package-Publish

on:
  push:
    branches:
      - master

jobs:
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci
      - run: npm run test

  package:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run publish

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: servicestack-client
          path: |
            ./dist/servicestack-client.mjs
            ./dist/servicestack-client.min.mjs
            ./dist/servicestack-client.umd.cjs

  publish:
    needs: package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - name: Bump version
        run: |
          VERSION=$(jq -r '.version' package.json)
          HASH=$(git rev-parse --short HEAD)
          NEW_VERSION="$VERSION-preview-$HASH"
          jq --arg nv "$NEW_VERSION" '.version=$nv' package.json > "tmp.json" && mv "tmp.json" "package.json"
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
