name: NPM Publish

# Trigger the workflow manually
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - run: npm ci
      - run: npm install uglifyjs -g
      - run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: servicestack-client
          path: |
            ./dist/index.d.ts
            ./dist/index.js
            ./dist/servicestack-client.min.js
            ./dist/servicestack-client.min.mjs
            ./dist/servicestack-client.mjs
            ./dist/servicestack-client.umd.js

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm install uglifyjs bump -g
      - run: npm release
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
